#!/bin/sh

pkill wofi

entries=" Normal\n Grab"

selected=$(echo $entries|wofi -x 430 --width 180 --height 125 --dmenu --cache-file /dev/null --prompt="River Mode Switch"| awk '{print tolower($2)}')

case $selected in
normal)
    riverctl enter-mode normal;;
toggle-float)
    riverctl toggle-float;;
grab)
    riverctl enter-mode grab;;
esac