#!/bin/sh

pkill wofi

entries=" Main\n Web\n Net\n Doc\n Term\n Media\n Desk"

selected=$(echo $entries|wofi -x 500 --width 240 --height 290 --dmenu --cache-file /dev/null --prompt="Move Toplevel To Tag.."| awk '{print tolower($2)}')

case $selected in
main)
    riverctl set-view-tags $((1 << (1 - 1)));;
web)
    riverctl set-view-tags $((1 << (2 - 1)));;
net)
    riverctl set-view-tags $((1 << (3 - 1)));;
doc)
    riverctl set-view-tags $((1 << (4 - 1)));;
term)
    riverctl set-view-tags $((1 << (5 - 1)));;
media)
    riverctl set-view-tags $((1 << (6 - 1)));;
desk)
    riverctl set-view-tags $((1 << (7 - 1)));;
esac