#!/bin/sh

pkill wofi

entries=" Move-Up\n Move-Down\n Toggle-Float\n Close"

selected=$(echo $entries|wofi -x 500 --width 240 --height 190 --dmenu --cache-file /dev/null --prompt="Toplevel Manager"| awk '{print tolower($2)}')

case $selected in
move-up)
    riverctl swap previous;;
move-down)
    riverctl swap next;;
toggle-float)
    riverctl toggle-float;;
close)
    riverctl close;;
esac