#!/bin/sh
pkill wofi
entries=" File\n VLC\n Telegram\n Firefox\n Leafpad\n Calculator\n Gucharmap\n Terminal"

selected=$(echo $entries|wofi -x 0 --width 240 --height 330 --dmenu --cache-file /dev/null --prompt=Applications | awk '{print tolower($2)}')

case $selected in
  file)
    pcmanfm;;
  vlc)
    chtag 1; VLC;;
  telegram)
    chtag 1; Telegram;;
  firefox)
    chtag 2; firefox-wayland;;
  leafpad)
    chtag 4; leafpad;;
  calculator)
    galculator;;
  gucharmap)
    chtag 4; gucharmap;;
  terminal)
    chtag 5; foot;;
esac