#!/bin/sh
pkill wofi
entries=" Logout\n⏾ Suspend\n Lock\n Reboot\n⏻ Shutdown"

selected=$(echo $entries|wofi -x 1710 --width 123 --height 225 --dmenu --cache-file /dev/null --prompt="Session Manager"| awk '{print tolower($2)}')

case $selected in
  logout)
    pgrep -U $USER | xargs kill -9;;
  suspend)
    exec doas -n zzz;;
  lock)
    exec lock;;
  reboot)
    exec doas -n reboot;;
  shutdown)
    exec doas -n poweroff;;
esac